- .gitmodules
- galpha2net/metadata.yaml
- galpha2net/values.yaml
- index.ts
- src/release.py
In this new testnet, we will attempt to upgrade from florence to alpha at block 42.
User-activated upgrade requires coordination between all bakers. This is achieved when all bakers use the `--network` URL hook. This is how it will look like:
```
{
"sandboxed_chain_name": "SANDBOXED_TEZOS",
"chain_name": "something",
"default_bootstrap_peers": [
"something",
],
"genesis": {
"block": "BMFCHw1mv3A71KpTuGD3MoFnkHk9wvTYjUzuR9QqiUumKGFG6pM",
"protocol": "PtYuensgYBb3G3x1hLLbCmcav8ue8Kyd2khADcL5LsT5R1hcXex",
"timestamp": "something"
"user_activated_upgrades": [
{
"level": 42,
"replacement_protocol": "ProtoALphaALphaALphaALphaALphaALphaALphaALphaDdp3zK"
}
]
},
"genesis_parameters": {
"values": {
"genesis_pubkey": "edpkuix6Lv8vnrz6uDe1w8uaXY7YktitAxn6EHdy2jdzq5n5hZo94n"
}
}
}
```
This way, every …
> galpha2net with user-activated upgrade from florence

- .gitmodules
- galpha2net/metadata.yaml
- galpha2net/values.yaml
- index.ts
* the chain was halting when we did user-activated upgrade at block 42,
instead we will do it at block 2048. Testing in isolation, I was able
to go to cycle 7 this way without seeing any chain halts.
The original issue encountered was:
```
May  6 18:47:17.040 - alpha.baking.forge: Error:
May  6 18:47:17.040 - alpha.baking.forge:   Storage error:
May  6 18:47:17.040 - alpha.baking.forge:     Missing key
'cycle/6/roll_snapshot'
```
* set the activation params to florence values for number of
endorsmenets per block/reward per block and endorsement/bond per block
and endorsement. Testing in isolation, I observed that these values
transition to suitable values for granada when the switchover happens.
> Galpha2net try 2

- .gitmodules
- granadanet/metadata.yaml
- granadanet/values.yaml
- index.ts
Specification for granadanet.
`values.yaml` contains the activation parameters. `metadata.yaml` contains the hostnames of the genesis bakers.
Please note:
* we will start off with florence and do a user-activated upgrade to granada at block 4095 (2 cycles in):
* because of that, the activation parameters that you see below are for florence. this is normal.
* ~before launch, I will be running single-baker tests to make sure the chain won't halt with these parameters.~ I ran a single-baker simulation which activated the upgrade and went further all the way to block 12000, and still going. There is a good chance these parameters are good and the chain won't halt
* blocks will be 30 second and will switch to 15 second after granada migration (mainnet blocks will switch from 1 min to 30 sec)
* …
> granadanet

- index.ts
this is to enable periodic chains' JSON to be published at stable links of the form https://teztnets.xyz/dailynet and https://teztnets.xyz/mondaynet (instead of https://teztnets.xyz/dailynet-2021-06-13 and https://teztnets.xyz/mondaynet-2021-06-07)
> match output property names to desired URLs

- .gitignore
- TezosChain.ts
- externalDns.ts
- index.ts
- route53.ts
closes #39 
- deploys external-dns
- external-dns creates the alias records for the p2p LB's and the faucet LB's
- faucet LB's have ssl enabled
> Create ingresses for faucets

- dailynet/values.yaml
Octez master has removed this param and hardcoded it.
closes #44
> Remove michelson_maximum_type_size param

- TezosChain.ts
Deploy a RPC ingress for every testnet. People won't have to run a node and sync the chain to interact with it, they just need a client and a faucet account.
> add rpc ingress

- idiazabalnet/values.yaml
- index.ts
This uncomments the `activation` section of the values.yaml, resulting
of creation of an activation job which activtes the chain. It also sets
the number of faucets back to 10000 so the faucet server will start.
This has to go `up` after the activation date and time in the
values.yaml file. Otherwise, activation will fail.
If activation fails for any reason, it's always possible to delete the
job, then `up --refresh` will create a fresh job that will attempt
activation again.
But activation is irreversible - once a block has been out and
propagated to peers, it's too late. Measure twice, cut once.
> step 3: activate

- idiazabalnet/README.md
- index.ts
Our regular faucet does not work, as commitments were not added to the parameters.json via the chain activation job. This was due a bug: https://github.com/oxheadalpha/tezos-k8s/pull/331
> Use Baking Bad's Telegram bot faucet for Idiazabalnet

- mondaynet/values.yaml
ECAD Labs is now running Mondaynet infrastructure. We would like to be included in the list of bootstrap bakers starting from the next network reset
> Add ECAD Labs address to the list of mondaynet bakers

- mondaynet/values.yaml
67% Baking power for oxheadbaker
33% Divided between rest
Removed inactive bakers.
> Update values.yaml (mondaynet)

- dailynet/values.yaml
- mondaynet/values.yaml
This MR updates the challenge period for SCORU to make it possible to
test cementing and refutation on the dailynet and the mondaynet.
> Update challenge period for SCORU

- dailynet/values.yaml
- mondaynet/values.yaml
Tests are easier to automate using predefined accounts.
This PR introduced such accounts in mondaynet and dailynet for the SCORU tests.
> Create accounts for SCORU tests

- dailynet/values.yaml
- mondaynet/values.yaml
We made two kind of changes:
1. Some constants have been updated to take into account last
minutes change in the design.  For instance, the limit in the
number of withdrawals authorized per batch has been lowered from
255 to 15, for security reasons.
2. Some constants have been drastically lowered to make it easier to
run end-to-end demos on teztnets.  This includes the sunset
level (set to ~11PM on dailynet, and Sunday on mondaynet), and
finality periods (set to 10 blocks instead of 40,000).
> Update protocol constants related to Transaction Rollups

- TezosChain.ts
- index.ts
rename ithaca namespace to ghostnet. this will cause the node to go down and be recreated from tarball.
Introduce an `aliases` mechanism to keep the old rpc/p2p load balancers alive.
> Ithacanet ghostnet

- dailynet/values.yaml
- mondaynet/values.yaml
This MR aims to add several accounts in the activation block to ease stress test. 
9 accounts with 10_000_000 tz are added.
I own the secret keys and I will distribute then to the people in charge of these accounts.
> Mondaynet/Dailynet: add accounts for stresstest

- TezosChain.ts
As of April 2023 AWS is **enabling** public access block on all new S3 buckets.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html#:~:text=it%20through%20ACLs.-,Important,-Starting%20in%20April
This prevents the application of public permissions to a bucket policy, among other things.
This fix disables the public access block and removes the acl `public-read` as by default this is not allowed on bucket creation.
> Fix AWS S3 public access block

- mondaynet/values.yaml
It can't be merged today because the network configuration is invalid with last monday's build - it was implemented this week.
> DAL for mondaynet

- TezosChain.ts
- index.ts
- pulumi/monitoring.ts
- when setting a chart version to install a remote chart, a local submodule chart would still try to be installed
- removed old node group not being used
- Use 'parent' to organize the monitoring resources properly
> Fix remote chart not working + re-configure node groups

- bootstrap_contracts/evm_bridge.json
- bootstrap_contracts/evm_fa12_contract.json
- dailynet/values.yaml
- index.ts
Mirror merge request of https://gitlab.com/tezos/tezos/-/merge_requests/9843.
This allows to have deposit working on dailynet, it's the same mechanism as for ghostnet. It needs to:
1. Update the smart rollup type, to `pair (pair bytes (ticket unit)) (pair nat bytes)`
2. On ghostnet, we use a ctez contract deployed by Marigold for the tokens. On dailynet, I added a dumb contract that respects the FA1.2 type of %approve and %transfer, making all transfers free.
3. Finally the EVM bridge that uses the contract from (2.) to deposit tokens.
The documentation on how to use is still lacking, but this will allow to have unlimited funds on the EVM rollup for dailynet easily.
I have no idea how I can test this merge request, it impacts the protocol's parameters so a bad encoding could make the …
> Evm deposit dailynet

- TezosChain.ts
- index.ts
- package-lock.json
- package.json
- auto-formatting
- properly waits for DAL svc loadbalancer's to be provisioned, and passes their ip's as pulumi Outputs to the tezos-k8s chart.
There are no pulumi out-of-the-box solutions for solving the awaiting problem. 
`OutputInstance` [`get()`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/#OutputInstance-get) methods for example, do not work during preview/updates. Pulumi Resource level `get()` methods don't work as they are meant for importing existing cloud resources into Pulumi's domain.
> Fix awaiter for DAL loadbalancers
